#!/bin/sh
# Creates random secrets in ./secrets (never overwrites an existing secret).
# The directory is private (0700); files are 0644 so the non-root users in
# the containers (postgres, UID 65532 api/operator-cli, UID 10001 importer
# and publisher) can read the bind-mounted secrets. Use your orchestrator's
# secret store in production.
#
#   db_*_password           database role passwords (db_monitor_password: the
#                           metrics exporter's karta_monitor role)
#   operator_token          operator API token with every scope (client side)
#   operator_monitor_token  operator API token with the status scope only
#   operator_tokens         what the publisher reads: NAME SCOPES SHA256(token)
#                           per line; derived from the two tokens above plus
#                           the lines of operator_tokens.extra, and rewritten
#                           in place on every run (it holds no usable secret;
#                           the running publisher reloads it by itself)
#   operator_tokens.extra   extra credentials (NAME SCOPES SHA256 per line),
#                           such as the intake watcher's or a person's intake
#                           command credential: managed with
#                           scripts/operator-credential.sh
#   metrics_tokens          what the API's metrics listener reads: the monitor
#                           credential's hash only; rewritten in place, so the
#                           running API picks a rotated token up by itself
#
# To rotate an operator token, delete its file and run this script again
# (`make rotate-operator-tokens`): the publisher and the API's metrics
# listener reload their credential files without a restart.
set -eu
cd "$(dirname "$0")/.."
umask 077
mkdir -p secrets
chmod 700 secrets
for name in db_superuser_password db_importer_password db_api_password db_monitor_password operator_token operator_monitor_token; do
  f="secrets/$name"
  if [ -s "$f" ]; then
    continue
  fi
  od -An -N32 -tx1 /dev/urandom | tr -d ' \n' > "$f"
  chmod 644 "$f"
  echo "created $f"
done
hash() { tr -d '\r\n' < "$1" | sha256sum | cut -d' ' -f1; }
# Replaces FILE's content with TMP's in place (same inode): Docker
# bind-mounts the file, and a replaced file would not be seen by the running
# container. The publisher refuses every request while the file does not
# parse, so a half-written file fails closed for a moment, never open.
install_in_place() {
  if ! cmp -s "$1" "$2" 2>/dev/null; then
    if [ -e "$2" ]; then
      cat "$1" > "$2"
    else
      mv "$1" "$2"
    fi
    chmod 644 "$2"
    echo "wrote $2"
  fi
  rm -f "$1"
}
tmp=$(mktemp secrets/.operator_tokens.XXXXXX)
{
  echo "# Operator credentials: NAME SCOPES SHA256-OF-TOKEN (generated by scripts/gen-secrets.sh)"
  echo "operator status,publish,rollback,cleanup $(hash secrets/operator_token)"
  echo "monitor status $(hash secrets/operator_monitor_token)"
  if [ -s secrets/operator_tokens.extra ]; then
    echo "# Extra credentials (secrets/operator_tokens.extra, scripts/operator-credential.sh)"
    grep -v '^[[:space:]]*\(#\|$\)' secrets/operator_tokens.extra || true
  fi
} > "$tmp"
install_in_place "$tmp" secrets/operator_tokens
# The API's metrics listener: only the monitoring credential (scope status).
# Rewritten in place (same inode): Docker bind-mounts the file, and a
# replaced file would not be seen by the running container.
tmp=$(mktemp secrets/.metrics_tokens.XXXXXX)
{
  echo "# Metrics credentials for the API's metrics listener (generated by scripts/gen-secrets.sh)"
  echo "monitor status $(hash secrets/operator_monitor_token)"
} > "$tmp"
install_in_place "$tmp" secrets/metrics_tokens
