#!/bin/sh
# Creates random secrets in ./secrets (never overwrites an existing secret).
# The directory is private (0700); files are 0644 so the non-root users in
# the containers (postgres, UID 65532 api/operator-cli, UID 10001 importer
# and publisher) can read the bind-mounted secrets. Use your orchestrator's
# secret store in production.
#
#   db_*_password           database role passwords
#   operator_token          operator API token with every scope (client side)
#   operator_monitor_token  operator API token with the status scope only
#   operator_tokens         what the publisher reads: NAME SCOPES SHA256(token)
#                           per line; derived from the two tokens above and
#                           rewritten on every run (it holds no usable secret)
#
# To rotate an operator token, delete its file, run this script again and
# restart the publisher (`make rotate-operator-tokens` does all three).
set -eu
cd "$(dirname "$0")/.."
umask 077
mkdir -p secrets
chmod 700 secrets
for name in db_superuser_password db_importer_password db_api_password operator_token operator_monitor_token; do
  f="secrets/$name"
  if [ -s "$f" ]; then
    continue
  fi
  od -An -N32 -tx1 /dev/urandom | tr -d ' \n' > "$f"
  chmod 644 "$f"
  echo "created $f"
done
hash() { tr -d '\r\n' < "$1" | sha256sum | cut -d' ' -f1; }
tmp=$(mktemp secrets/.operator_tokens.XXXXXX)
{
  echo "# Operator credentials: NAME SCOPES SHA256-OF-TOKEN (generated by scripts/gen-secrets.sh)"
  echo "operator status,publish,rollback,cleanup $(hash secrets/operator_token)"
  echo "monitor status $(hash secrets/operator_monitor_token)"
} > "$tmp"
chmod 644 "$tmp"
if ! cmp -s "$tmp" secrets/operator_tokens 2>/dev/null; then
  mv "$tmp" secrets/operator_tokens
  echo "wrote secrets/operator_tokens"
else
  rm -f "$tmp"
fi
