#!/bin/sh
# Adds, lists and removes extra operator API credentials (Stage 5): narrow
# credentials such as the intake watcher's (scope intake_watch) or one
# person's intake command credential (scope intake_submit). Each is a line
# NAME SCOPE SHA256-OF-TOKEN in secrets/operator_tokens.extra; the script then
# runs scripts/gen-secrets.sh, which rewrites secrets/operator_tokens in place,
# and the running publisher reloads it at its next request: a removed
# credential is refused at once, without restarting the publisher (a running
# build is not interrupted).
#
#   scripts/operator-credential.sh add NAME SCOPE [TOKEN_FILE]
#       registers a credential NAME with SCOPE. TOKEN_FILE (default
#       secrets/NAME.token) is created with a new random token unless it
#       exists. The token file is the credential: give it to its holder only.
#   scripts/operator-credential.sh remove NAME [TOKEN_FILE]
#       unregisters NAME and deletes TOKEN_FILE (default secrets/NAME.token).
#   scripts/operator-credential.sh list
#
# SCOPE is intake_watch, intake_submit or status; an intake scope is always
# the credential's only scope. NAME: a lower-case letter, then up to 31
# lower-case letters, digits, _ or -; not operator or monitor (generated by
# scripts/gen-secrets.sh).
set -eu
cd "$(dirname "$0")/.."
umask 077
extra=secrets/operator_tokens.extra

usage() {
  echo "usage: $0 add NAME intake_watch|intake_submit|status [TOKEN_FILE]" >&2
  echo "       $0 remove NAME [TOKEN_FILE]" >&2
  echo "       $0 list" >&2
  exit 2
}

valid_name() {
  printf '%s' "$1" | grep -Eq '^[a-z][a-z0-9_-]{0,31}$' && [ "$1" != operator ] && [ "$1" != monitor ]
}

registered() { [ -f "$extra" ] && awk -v n="$1" '$1 == n { found = 1 } END { exit !found }' "$extra"; }

# Writes the extra file without NAME's line (in place, private).
drop() {
  tmp=$(mktemp secrets/.operator_tokens.extra.XXXXXX)
  if [ -f "$extra" ]; then
    awk -v n="$1" '$1 != n' "$extra" > "$tmp"
  fi
  cat "$tmp" > "$extra"
  rm -f "$tmp"
}

[ $# -ge 1 ] || usage
cmd=$1
shift
case "$cmd" in
add)
  [ $# -ge 2 ] && [ $# -le 3 ] || usage
  name=$1 scope=$2 file=${3:-secrets/$1.token}
  valid_name "$name" || { echo "invalid credential name: $name" >&2; exit 2; }
  case "$scope" in intake_watch | intake_submit | status) ;; *) echo "scope must be intake_watch, intake_submit or status" >&2; exit 2 ;; esac
  [ -d secrets ] || ./scripts/gen-secrets.sh > /dev/null
  if [ ! -s "$file" ]; then
    od -An -N32 -tx1 /dev/urandom | tr -d ' \n' > "$file"
    # Readable by the container user (UID 65532) through a bind mount; the
    # secrets directory itself stays private (0700).
    chmod 644 "$file"
    echo "created $file"
  fi
  hash=$(tr -d '\r\n' < "$file" | sha256sum | cut -d' ' -f1)
  line="$name $scope $hash"
  if registered "$name"; then
    if awk -v l="$line" '$0 == l { found = 1 } END { exit !found }' "$extra"; then
      echo "$name is already registered with scope $scope"
      ./scripts/gen-secrets.sh > /dev/null
      exit 0
    fi
    echo "$name is already registered with another scope or token; remove it first" >&2
    exit 1
  fi
  touch "$extra"
  chmod 600 "$extra"
  echo "$line" >> "$extra"
  ./scripts/gen-secrets.sh
  echo "registered $name ($scope); token file: $file"
  ;;
remove)
  [ $# -ge 1 ] && [ $# -le 2 ] || usage
  name=$1 file=${2:-secrets/$1.token}
  valid_name "$name" || { echo "invalid credential name: $name" >&2; exit 2; }
  registered "$name" || { echo "$name is not registered in $extra" >&2; exit 1; }
  drop "$name"
  ./scripts/gen-secrets.sh
  rm -f "$file"
  echo "removed $name: the publisher refuses it from its next request on"
  ;;
list)
  [ $# -eq 0 ] || usage
  [ -s "$extra" ] && awk '!/^[[:space:]]*(#|$)/ { print $1, $2 }' "$extra" || true
  ;;
*)
  usage
  ;;
esac
